### ISSUE TITLE
Request for new 0.5 release 

### ISSUE THREAD

**Issue by mrniranjan** [aoh/radamsa#20]
Greetings, 

My name is Niranjan , packager of radamsa in fedora, I would like to know if you could create new release tag 0.5 , since there has been lot of changes from the last release 0.4. 

I would like to update the radamsa package in fedora to the latest changes.

**Comment by aoh** [comment]
Hi, 

New version is now available.

**Comment by aoh** [comment]
Github seems to have the added custom releases, so I added a prebuilt version of radamsa.c to radamsa-0.5.tar.gz, and will also do so for later releases. You can keep using the autogenerated tarballs as before, but release versions of radamsa can now be built without owl.
