### ISSUE TITLE
Internal compiler error

### ISSUE THREAD

**Issue by juhakivekas** [aoh/radamsa#22]
When building radamsa from the master branch `5c67b3c9f5f00aa8304ec62be3dad2ebf2aa66e1` my gcc has an internal error. The error comes from the following line:

```
gcc -Wall -O2 -o bin/radamsa radamsa.c
```

And the error message (the only one I get) is quite generic:

```
gcc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
```

As it seems to be a very speical case of using the C language, I decided to ask you if this is a known issue or something wild and crazy that shouldn't happen. If this is unknown and hard to replicate, then maybe I'll make a bug report to gcc. My `gcc --version` shows this:

```
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.1) 5.4.0 20160609
```

The issue persists in the v0.5 tagged commit `3f53d530499e66e663803d857f2ba4729408e440`.

**Comment by aoh** [comment]
Can you check whether `make clean; make OFLAGS=-O1` makes a difference?

**Comment by juhakivekas** [comment]
Yes that works, amazing but surprising.

**Comment by aoh** [comment]
Ok. You likely have some new gcc optimization going quadratic or a bug in the compiler. OFLAG -O1 reduces optimization in owl (the default in radamsa is -O2), which leads to less C-code being generated, which makes things easier for gcc.

In any case, the bug doesn't seem to be in this castle. Probably worth filing as a gcc issue.
