### ISSUE TITLE
combining inputs?

### ISSUE THREAD

**Issue by kokanin** [aoh/radamsa#23]
mkdir bla; echo a > bla/a; echo b > bla/b; for i in `seq 100` ; do echo ; radamsa -r bla | xxd ; done

While i get the wonderfully mangled output, I never get a combined output of a and b - is this possible, or is the initial overhead of deducing structures and such just too heavy when handling multiple inputs?

**Comment by aoh** [comment]
You need to create more than one output at a time for radamsa to have time to pick up information form other samples. E.g.:

$ echo 'aaaa xxxxxx 111111' > sample-1
$ echo 'bbbb xxxxxx 222222' > sample-2
$ radamsa sample-[12] -n 100 | grep "^aa\* xx\* 22*$"
aaaa xxxxxx 222222
$ echo '<foo>test</foo>' > x-1
$ echo '<bar>test</bar>' > x-2
$ radamsa x-[12] -n 20 | grep "<foo><bar>"
<foo><bar><foo><ar><foo><foo><foo>test</foo></foo></foo></foo><foo><ar><foo><foo><bar><foo>test</foo></foo></foo></foo></foo>

**Comment by kokanin** [comment]
Thanks, this works. It's hard not to cringe when I consider how many cycles were spent not doing this.
