### ISSUE TITLE
Dialect and implementation of Scheme?

### ISSUE THREAD

**Issue by joereynolds** [aoh/radamsa#27]
Hey!

I'm interested in possibly contributing to this (if I can wrap my head around it)
What dialect and implementation of Scheme are you using? I'm unfamiliar with some of what I see

**Comment by aoh** [comment]
Hi,

Contributions and contributors are welcome. The Scheme being used is Owl Lisp, which is essentially R7RS Scheme - mutable data structures + multithreading and a few extra data structures. Some initial documentation is available at https://haltp.org/n/owl.
