### ISSUE TITLE
bug: not removing alarm on io error, if there

### ISSUE THREAD

**Issue by vah13** [aoh/radamsa#34]
Hi.
In fuzzing time, I from time to time getting this error 

bug: not removing alarm on io error, if there

what do you think, why I getting it and how I can fix it?

**Comment by aoh** [comment]
Hi, 

Cool, a bug. I don't recall seeing that . Have you been able to reproduce it? Do you recall if it happens always in file, TCP, stdout or some particular input or output combination?

**Comment by vah13** [comment]
yes, this is a request input parameter 
radamsa.exe req.txt req2.txt -n 1000000 -s 1111 -o 192.168.72.142:1111

req.txt
```
GET / HTTP/1.1
Host: 127.0.0.1:1111
Connection: keep-alive
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4
```

req2.txt
```
POST / HTTP/1.1
Host: 127.0.0.1:1111
Connection: keep-alive
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4

aaaa


```

**Comment by aoh** [comment]
Great. I'll have a look when I have some spare hacking time. That is coming from https://github.com/aoh/owl-lisp/blob/master/owl/io.scm#L693 . I/O code got updated in owl some time ago, and radamsa here ends up using it with timeouts in a way that hasn't been tested and fully implemented yet, for which case there is a warning print to stderr.

**Comment by aoh** [comment]
I/o alarm removal on input error added to owl, so the fix will be in next radamsa version. A test is needed also in owl, but I didn't find a way to test for an i/o error portably yet.

Thanks for the bug! With bad luck the issue might break nondeterminism (read from port with timeout where connection is broken and i/o timeout is signaled when the same fd is used by another connect), and the print was annoying :)
