### ISSUE TITLE
a unknown bug in network fuzzing time

### ISSUE THREAD

**Issue by vah13** [aoh/radamsa#39]
Hi.
When I use radamsa for fuzzing the network protocol I got a some issue.

When I launched radamsa with this parameters

> radamsa need_fuzz_protocol.bin -s 3 -n 1000000 -o server_ip:server_port -vv

He generate only 4 case
![image](https://cloud.githubusercontent.com/assets/7976421/23397895/5d5ab1be-fdab-11e6-8b48-01f156c5c1fd.png)
another seed
![image](https://cloud.githubusercontent.com/assets/7976421/23397940/91a6cbce-fdab-11e6-91d7-b92dad409649.png)

But if I generate test case's in a folder, radamsa successfully generated all 100000 cases.

**Comment by aoh** [comment]
Hi. Thanks! Sounds like a bug, but could also be radamsa giving up too early of the other end is not accepting connections. If latter, it should be clear about at least in verbose mode and the retry count and interval should be configurable.

Can you check whether the same number of testcases is generated always when the same seed is given on command line?

**Comment by vah13** [comment]
> Can you check whether the same number of testcases is always generated when the same seed is given on command line?

Hi, yeah. In same seed, I tried fuzz 6-7 time, and always the radamsa generated equal testcases. 
May will help you, but when I launched radamsa with gdb I got 0177 error code.

**Comment by aoh** [comment]
Reproduced locally.
