### ISSUE TITLE
something available for ARM

### ISSUE THREAD

**Issue by srikanth007m** [aoh/radamsa#4]
Hello, 

Does this tool works for ARM? Though i didn't see ARM as supported platform. But just wanted to know if it works or not.

**Comment by srikanth007m** [comment]
Tried myself to cross compile for ARM and able to do it.

**Comment by aoh** [comment]
Glad to hear it worked. Onboard compilation on smaller devices (e.g. first gen raspberries) needed -O1 or no -O to OFLAGS, to avoid the C compiler from taking tons of memory, but otherwise there should be no issues.
