### ISSUE TITLE
Can it be installed on a raspberry pi ?

### ISSUE THREAD

**Issue by meeeo** [aoh/radamsa#50]
I tried to make it on a raspberry pi zero w, always failed, is it lack of memory or what, can't it?
Thank you.
![img_7390](https://user-images.githubusercontent.com/5188710/35560097-62cbb4fa-05e7-11e8-8f5d-98eeae495773.JPG)
![img_7393](https://user-images.githubusercontent.com/5188710/35560098-6318a6e8-05e7-11e8-980b-446acf206ebf.JPG)

**Comment by aoh** [comment]
Your C-compiler is indeed running out of memory. You can get around that by temporarily adding more swap space, or by removing radamsa.c and and recompiling it with `make OFLAGS=-O1` to make a smaller radamsa.c. You can also make the smaller radamsa.c on another machine, copy it to raspberry and get it running with `cc -O2 -o radamsa radamsa.c`.

**Comment by meeeo** [comment]
Thank you, I'll try it later and let you know.

**Comment by meeeo** [comment]
I made a smaller radamsa.c on pi itself, thank you.
Thank you. 
<img width="1440" alt="2018-01-31 15 27 37" src="https://user-images.githubusercontent.com/5188710/35610194-563e3226-069b-11e8-8252-744a871ec644.png">
<img width="1440" alt="2018-01-31 15 27 40" src="https://user-images.githubusercontent.com/5188710/35610195-56b809de-069b-11e8-87bd-835e0a6c2d75.png">

**Comment by aoh** [comment]
Great! Closing as the issue seems to have been resolved.
