### ISSUE TITLE
amount of fuzzed objects differ from count parameter

### ISSUE THREAD

**Issue by nmerkulo** [aoh/radamsa#55]
I am running radamsa v0.6 like this:
`echo "no" | ./radamsa --seed 1171423923758331160377055 -n 100 -v --output-template {{{%f}}},`

and the result I get is:
`Random seed: 1171423923758331160377055
{{{n�o
}}}, - 1: 14b
{{{     no
}}}, - 2: 11b
{{{}}}, - 3: 7b
{{{n� ������o
}}}, - 4: 29b
{{{no�
}}}, - 5: 14b
{{{no���
}}}, - 6: 16b
{{{no�
}}}, - 7: 14b
{{{שּׁnไo
}}}, - 8: 16b
{{{noᅟ
}}}, - 9: 13b
{{{nooooooooooooooooooooooooooooooooooooooo�oooooooooooooooo
                                                             oooooooooooooooooooooooooooooooooooooʲ�������������������� ���������������������������������������������������������������������������������������
}}}, - 10: 218b
{{{noooooooooo�oooooooooooo�ooooooooooooooooooooooooooooooooooo�oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
}}}, - 11: 272b
{{{no�
}}}, - 12: 14b
{{{ßno
}}}, - 13: 12b
{{{�no
n￿o
}}}, - 14: 20b
no{
}}}, - 15: 11b
{{{nXnonononoonnononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononononono
}}}, - 16: 772b
{{{�������������no
}}}, - 17: 26b
����/�+/vvv ��vvvvvvvv�����
}}}, - 18: 425b
}}}, - 19: 8b
{{{��o
n�
o�oon�
}}}, - 20: 21b
{{{no
no
}}}, - 21: 13b
{{{nnnnnnnnnnnnnnnnnno
}}}, - 22: 27b
{{{no
}}}, - 23: 10b
{{{oo
}}}, - 24: 10b`

The return code is also non-zero. OS is RHEL 8.7.

**Comment by aoh** [comment]
Thanks! This was a bug. It should now be fixed in the default branch.

**Comment by nmerkulo** [comment]
I confirm -- problem solved. Thank you!
