### ISSUE TITLE
Consider adding a NEWS file to the repo

### ISSUE THREAD

**Issue by brarcher** [aoh/radamsa#8]
It may be important to inform users of Radamsa of relevant changes between released versions. This may include the addition of addition patterns, new features, bug fixes, etc. Typically this is accomplished using a NEWS file in the repository or release tarball.

It is not obvious between revisions 0.3 and 0.4 what changed, and why one should be interested in updating. The inclusion of a NEWS file will help inform users of such changes.

The GNU Coding Standard gives recommendations for the content of a NEWS file. This is available here:
[NEWS-File](https://www.gnu.org/prep/standards/standards.html#NEWS-File).

Kindly consider adding and maintaining a NEWS file at relevant milestones of the Radamsa project.

**Comment by aoh** [comment]
Makes sense. I'll leave this open and add it during next release.

**Comment by aoh** [comment]
0.5 was released and NEWS file was added while at it.
